[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "bleach>=6.2.0",
    "flask>=3.1.2",
    "flask-login>=0.6.3",
    "markupsafe>=3.0.2",
    "werkzeug>=3.1.3",
]
